version: '3'

x-kafka-broker-env-base: &kafka_broker_env_base
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  # KAFKA_OPTS: -javaagent:/etc/kafka/jmx_prometheus_javaagent-0.15.0.jar=7071:/etc/kafka/metrics/jmx-exporter-kafka.yml
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
  KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  KAFKA_CONFLUENT_TOPIC_REPLICATION_FACTOR: 2

x-kafka-broker-base: &kafka_broker_base
  image: kafka-jmx
  healthcheck:
    test: ['CMD-SHELL', 'kafka-topics.sh --bootstrap-server localhost:9092 --list']
    start_period: 30s
    timeout: 5s
    interval: 3s
    retries: 100
  depends_on:
    zookeeper:
      condition: service_healthy

services:
  zookeeper:
    image: zookeeper-jmx
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      EXTRA_ARGS: -javaagent:/etc/zookeeper/jmx_prometheus_javaagent-0.15.0.jar=7072:/etc/zookeeper/metrics/jmx-exporter-zookeeper.yml
    healthcheck:
      test: jps -l | grep zookeeper || exit 1
      start_period: 1s
      timeout: 5s
      interval: 3s
      retries: 100

  kafka1:
    <<: *kafka_broker_base
    container_name: kafka1
    ports:
      - "19092:19092"
    environment:
      <<: *kafka_broker_env_base
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:19092,INTERNAL://kafka1:9092

  kafka2:
    <<: *kafka_broker_base
    container_name: kafka2
    ports:
      - "29092:29092"
    environment:
      <<: *kafka_broker_env_base
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:29092,INTERNAL://kafka2:9092

  kafka3:
    <<: *kafka_broker_base
    container_name: kafka3
    ports:
      - "39092:39092"
    environment:
      <<: *kafka_broker_env_base
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:39092,INTERNAL://kafka3:9092

  # prometheus:
  #   image: prom/prometheus:v2.49.1
  #   container_name: prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   ports:
  #     - 9090:9090
  #   restart: unless-stopped
  #   volumes:
  #     - ./prometheus:/etc/prometheus
  #     - ./prometheus/prom_data:/prometheus
  #   depends_on:
  #     kafka1:
  #       condition: service_healthy
  #     kafka2:
  #       condition: service_healthy
  #     kafka3:
  #       condition: service_healthy
